[theme]
primaryColor="#145efc"      # Azul SIG Sky para destaques (botões, sliders)
backgroundColor="#f2efeb"   # Fundo principal SIG Sand 1
secondaryBackgroundColor="#ffffff" # Barra lateral Branca
textColor="#000000"         # Texto padrão preto
font="sans serif"
